name: 'Build, Test, and Release Updates to Google Artifact Registry'

on:
  workflow_dispatch:

jobs:
  # Job 1: Build and release to Google Artifacts
  build-and-release-to-Google-Artifacts:
    name: 'Build, Test and Release'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    env:
      TZ: Europe/Madrid  # Set the timezone to your local timezone
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # Step 1: Clone the source repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Go
      - name: Setting up Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      # Step 3: Build all Go files
      - name: Build All Go Files
        id: build_step
        run: |
          echo "Building all Go files in the directory..."
          mkdir -p build
          find . -type f -name "*.go" | while read -r file; do
            echo "Building $file..."
            output_name=$(basename "$file" .go)
            go build -o "build/$output_name" "$file"
          done

      # Step 4: Show Build Results
      - name: List Build Output
        run: |
          echo "Build outputs:"
          ls -lh build/

      # Step 5: Simulating that some testing are done 
      - name: Simulating that some testings and checks are done
        run: |
          echo "Simulating that some testings and checks are done"

      # Step 6: Compress Build Artifacts
      - name: Compress Build Artifacts
        run: |
          service_name=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)
          zip_name="${service_name}.zip"
          echo "zip_name=$zip_name" >> $GITHUB_ENV
          zip -r "$zip_name" build/
          
      # Step 7: Compute the SHA256
      - name: Compute the SHA256 of the .zip
        run: |
          echo "Computing SHA256 checksum of the .zip"
          digest=$(sha256sum "${{ env.zip_name }}" | awk '{ print $1 }')
          echo "digest=$digest" >> $GITHUB_ENV
          echo "SHA256 checksum is: $digest"

      # Step 8: Generate Calendar Versioning
      - name: Generate Calendar Versioning
        id: calendar_version
        run: |
          tag="v$(date +'%Y.%m.%d')-${{ env.digest }}"
          echo "tag=$tag" >> $GITHUB_ENV
          echo "Generated tag: $tag"

      # Step 9: Debug Generated Tag
      
      - name: Debug Generated Tag
        run: |
          echo "Tag is: ${{ env.tag }}"
        
      # Step 10: Verifying GitHub Token
      - name: Verify GITHUB_TOKEN
        run: |
          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
              echo "Error: GITHUB_TOKEN is not set."
              exit 1
          else
              echo "GITHUB_TOKEN is available."
          fi

      # Step 11: Create a release
      - name: Create a GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.tag }}
          release_name: "Tunnel-integration ${{ env.tag }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Release generated by GitHub Actions.
            This includes the build artifacts of tunnel-integration service.
          draft: false
          prerelease: false

      # Step 12: Upload the build artifacts to the release
      - name: Upload the build artifacts to the release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.zip_name }}
          asset_name: ${{ env.zip_name }}
          asset_content_type: application/zip

      # Step 13: Login to Google Cloud Registry
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with: 
          token_format: access_token
          workload_identity_provider: projects/185640679849/locations/global/workloadIdentityPools/github/providers/github-prov
          service_account: github-actions-auth@polished-medium-445107-i9.iam.gserviceaccount.com
          access_token_lifetime: '600s'

      # Step 14: Upload the artifacts to Google Artifact Registry
      - name: Pushing the .zip to Google Artifact Registry
        id: pushing-GAR
        run: |
          echo "Uploading the released artifact from GitHub to Google Artifact Registry..."
          # Ensure `service_name` and `zip_name` are correctly set
          service_name=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)
          file=${{ env.zip_name }}
          
          echo "Processing artifact file: $file for service: $service_name"

          # Retrieve the version from the release tag
          version=${{ env.tag }}

          echo "$version"

          # Push the artifact to Google Artifact Registry
          gcloud artifacts generic upload \
            --repository=nebula-storage \
            --location=europe-southwest1 \
            --project=polished-medium-445107-i9 \
            --package="$service_name" \
            --version="$version" \
            --source="$file"

          echo "Successfully uploaded $file to Google Artifact Registry"


