name: 'Release Last Uploaded Binary of Google Artifact Registry to Clients'

on: 
  workflow_dispatch:  # Manually triggered for flexibility

jobs:
  push-target-file:
    name: 'Push Target File to TUF Repository'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      # Step 1: Clone the Target Repository
      - name: Clone Target Repository
        env:
          TUF_REPO_URL: ${{ secrets.TUF_REPO_URL }}
        run: |
          echo "Cloning the TUF repository..."
          git clone "$TUF_REPO_URL" tuf-repo
          cd tuf-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 2: List all the -index.json files in updates-not-released
      - name: List the -index.json files in updates-not-released-index
        run: |
          echo "Listing the -index.json files in the 'updates-not-released-index' folder..."
          find tuf-repo/updates-not-released-index -type f -name '*-index.json'

      # Step 3: Compute SHA256 hash of the file in the updates-not-released folder
      - name: Get the Branch Name
        id: compute-branch
        run: |
          date=$(date +'%Y.%m.%d-%H.%M.%S')
          branch_name="sign/Updates-${date}"
          echo "Branch name: $branch_name"

          # Export the branch name for later steps
          echo "::set-output name=branch::$branch_name"
        shell: bash

      # Step 4: Create and Checkout the Computed Branch
      - name: Create and Checkout New Branch
        run: |
          cd tuf-repo
          branch_name=${{ steps.compute-branch.outputs.branch }}
          git checkout -b $branch_name
          echo "Created and switched to branch $branch_name."

      # Step 5: Move index.json to the Targets Folder
      - name: Move ${GITHUB_REPOSITORY}'s index file to its corresponding repository
        run: |
          echo "${GITHUB_REPOSITORY}"
          repo_name=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)
          filename="${repo_name}-index.json"
          echo "File name: $filename"

          # Remove the '-index.json' suffix to get 'something'
          name=$(echo "$filename" | sed 's/-index\.json$//')

          echo "Moving $filename from updates-not-released-index to targets/$name..."
          
          # Create the target directory if it doesn't exist
          mkdir -p "targets/$name"
          
          # Move the file to the new directory
          mv "tuf-repo/updates-not-released-index/$filename" "tuf-repo/targets/$name"

          echo "Moved $filename to targets/$name folder."

      # Step 6: Commit and Push Changes to the TUF Repository
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.TUF_REPO_PAT }}
        run: |
          cd tuf-repo
          git add targets/
          git commit -m "Move index.json from updates-not-released-index to targets/"
          git push origin ${{ steps.compute-branch.outputs.branch }}
