name: 'Release Last Uploaded Binary of Google Artifact Registry to Clients'

on: 
  workflow_dispatch:  # Manually triggered for flexibility

jobs:
  push-target-file:
    name: 'Push Target File to TUF Repository'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:

      # Step 1: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with: 
          token_format: access_token
          workload_identity_provider: projects/185640679849/locations/global/workloadIdentityPools/github/providers/github-prov
          service_account: github-actions-auth@polished-medium-445107-i9.iam.gserviceaccount.com
          access_token_lifetime: '600s'

      # Step 2: Reading the version of the last uploaded release to Google Artifact Registry
      - name: Reading the last uploaded release to Google Artifact Registry
        run: |
          service_name=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)
          echo "SERVICE_NAME=$service_name">>$GITHUB_ENV
          echo "Getting the last released version to Google Artifact Registry"
          VERSION=$(gcloud artifacts versions list \
            --location=europe-southwest1 \
            --project=polished-medium-445107-i9 \
            --repository=nebula-storage \
            --package=$service_name \
            --sort-by=~createTime \
            --limit=1 \
            --format="value(VERSION)")
          echo "Latest version is $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          # From the version, the SHA256 can be obtained
          sha256=$(echo "${VERSION}" | cut -d '-' -f2)

          echo "The sha256 is $sha256"

          echo "SHA256=$sha256">>$GITHUB_ENV
      
      # Step 3: Reading the files that are inside the latest uploaded version
      - name: Reading the files that are inside this uploaded last version
        run: |
          echo "Listing files in version $VERSION"
          FILES=$(gcloud artifacts files list \
            --location=europe-southwest1 \
            --project=polished-medium-445107-i9 \
            --repository=nebula-storage \
            --package=$SERVICE_NAME  \
            --version=$VERSION \
            --format="value(name)")
          echo "Files in the version:"
          echo "$FILES"
          echo "FILES=$FILES" >> $GITHUB_ENV

      # Step 4: Computing the size of the listed files
      - name: Compute File Sizes in Latest Version
        id: compute_sizes
        run: |
          echo "Listing files and their sizes in version $VERSION"
          FILE_SIZES=$(gcloud artifacts files list \
            --location=europe-southwest1 \
            --project=polished-medium-445107-i9 \
            --repository=nebula-storage \
            --package=$SERVICE_NAME \
            --version=$VERSION \
            --format="csv[no-heading](name,sizeBytes)")
          
          echo "Files and sizes:"
          echo "$FILE_SIZES"

          # Compute total size
          TOTAL_SIZE=$(echo "$FILE_SIZES" | awk -F',' '{sum += $2} END {print sum}')
          echo "Total size of files: $TOTAL_SIZE bytes"
          echo "TOTAL_SIZE=$TOTAL_SIZE" >> $GITHUB_ENV

      # Step 5: Clone the Target Repository
      - name: Clone Target Repository
        env:
          TUF_REPO_URL: ${{ secrets.TUF_REPO_URL }}
        run: |
          echo "Cloning the TUF repository..."
          git clone "$TUF_REPO_URL" tuf-repo
          cd tuf-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 6: Create or Update index.json in the Targets Folder
      - name: Create or Update index.json in the Targets Folder
        run: |
          cd tuf-repo

          # Construct the filename and target folder
          repo_name=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)
          filename="${repo_name}-index.json"
          echo "File name: $filename"

          # Use SERVICE_NAME to determine the target folder
          target_folder="targets/$SERVICE_NAME"
          echo "Target folder: $target_folder"

          # Ensure the target folder exists
          mkdir -p "$target_folder"

          # Full path to the index.json file
          index_path="$target_folder/$filename"

          # Check if the index.json file exists
          if [[ -f "$index_path" ]]; then
            echo "$index_path exists. Updating the content."
          else
            echo "$index_path does not exist. Creating a new file."
            echo '{}' > "$index_path"  # Create a new empty JSON file if it doesn't exist
          fi

          # Update the index.json file using jq
          jq --arg file "$SERVICE_NAME" \
            --arg length "$TOTAL_SIZE" \
            --arg sha256 "$SHA256" \
            --arg version "$VERSION" \
            --arg path "https://artifactregistry.googleapis.com/download/v1/projects/polished-medium-445107-i9/locations/europe-southwest1/repositories/nebula-storage/files/${SERVICE_NAME}:${VERSION}:${SERVICE_NAME}.zip:download?alt=media" \
            '.[$file] = {length: ($length | tonumber), path: $path, hashes: {sha256: $sha256}, version: $version}' "$index_path" > tmp.json && mv tmp.json "$index_path"

          echo "Updated or created $index_path"

      # Step 7: Commit and Push Changes
      - name: Commit and Push Changes
        env:
            TUF_REPO_PAT: ${{ secrets.TUF_REPO_PAT }}
        run: |
            cd tuf-repo
            git add targets/
            git commit -m "Create or update index.json in the targets/$SERVICE_NAME folder"
            git push https://x-access-token:${TUF_REPO_PAT}@github.com/sorayaormazabalmayo/TUF_Repository_Yubikey_Vault.git ${{ steps.compute-branch.outputs.branch }}
